### PR TITLE
added `last` function

### PR DESCRIPTION
**Pull request by ptitluc**

### CODE REVIEW

**Comment by reddec** [comment]
Thank you for the PR!
Can we do it by `tail -n 1 | ...`?

**Comment by ptitluc** [comment]
hi, you're welcome :)
Sure we can do it with tail, I just thought it was more fun to stick with sed for the sake of consistency.
Else something like this should do :
`tail -n 1 | cut -d ' ' -f 2 | base64 -d`

**Comment by reddec** [comment]
Yep, like that :smile: 

If you are ready for hardcore - you can make automatic logic: if no tail (:eyes:), use sed

**Comment by ptitluc** [comment]
this is a possibility but ... .what is wrong with using sed only, then ?

**Comment by reddec** [comment]
You right)

**Pull request merged**
